### ISSUE TITLE
Rocket Overlapping With Abhiyaan Logo at home Screen Before Time

### ISSUE THREAD

**Issue by Rahul-AkaVector** [psantosh16/abhiyaan_home#19]
Rocket animation overlapping 
![Screenshot (53)](https://user-images.githubusercontent.com/90543113/226985428-22002cd3-8f4e-4085-89a9-e8a99b13e48f.png)
before completing logo rotation at home page , increase time if possible for rocket revealing from behind the logo

**Comment by OmkarDate29** [comment]
Resolve
